/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VaultDeliveriesRouteImport } from './routes/vault-deliveries'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedemptionsRouteImport } from './routes/redemptions'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PregradeRouteImport } from './routes/pregrade'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddToVaultRouteImport } from './routes/add-to-vault'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as ServiceOrdersIndexRouteImport } from './routes/service-orders.index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AchievementsIndexRouteImport } from './routes/achievements.index'
import { Route as ServiceProviderProviderIdRouteImport } from './routes/service-provider.$providerId'
import { Route as ServiceOrdersOrderIdRouteImport } from './routes/service-orders.$orderId'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerNewRouteImport } from './routes/seller.new'
import { Route as SellerSellerIdRouteImport } from './routes/seller.$sellerId'
import { Route as ProfileKycRouteImport } from './routes/profile.kyc'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as MarketListingIdRouteImport } from './routes/market.$listingId'
import { Route as CheckoutListingIdRouteImport } from './routes/checkout.$listingId'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as AchievementsSlugRouteImport } from './routes/achievements.$slug'
import { Route as VaultItemsItemIdRouteImport } from './routes/vault.items.$itemId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultDeliveriesRoute = VaultDeliveriesRouteImport.update({
  id: '/vault-deliveries',
  path: '/vault-deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedemptionsRoute = RedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PregradeRoute = PregradeRouteImport.update({
  id: '/pregrade',
  path: '/pregrade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddToVaultRoute = AddToVaultRouteImport.update({
  id: '/add-to-vault',
  path: '/add-to-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const ServiceOrdersIndexRoute = ServiceOrdersIndexRouteImport.update({
  id: '/service-orders/',
  path: '/service-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AchievementsRoute,
} as any)
const ServiceProviderProviderIdRoute =
  ServiceProviderProviderIdRouteImport.update({
    id: '/service-provider/$providerId',
    path: '/service-provider/$providerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceOrdersOrderIdRoute = ServiceOrdersOrderIdRouteImport.update({
  id: '/service-orders/$orderId',
  path: '/service-orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNewRoute = SellerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSellerIdRoute = SellerSellerIdRouteImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => SellerRoute,
} as any)
const ProfileKycRoute = ProfileKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => ProfileRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const MarketListingIdRoute = MarketListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketRoute,
} as any)
const CheckoutListingIdRoute = CheckoutListingIdRouteImport.update({
  id: '/checkout/$listingId',
  path: '/checkout/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CampaignsRoute,
} as any)
const AchievementsSlugRoute = AchievementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AchievementsRoute,
} as any)
const VaultItemsItemIdRoute = VaultItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/add-to-vault': typeof AddToVaultRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/extract': typeof ExtractRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pregrade': typeof PregradeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ratings': typeof RatingsRoute
  '/redemptions': typeof RedemptionsRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/scanner': typeof ScannerRoute
  '/seller': typeof SellerRouteWithChildren
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/stores': typeof StoresRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault-deliveries': typeof VaultDeliveriesRoute
  '/wishlist': typeof WishlistRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/profile/kyc': typeof ProfileKycRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/new': typeof SellerNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/service-orders/$orderId': typeof ServiceOrdersOrderIdRoute
  '/service-provider/$providerId': typeof ServiceProviderProviderIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/market/': typeof MarketIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/service-orders/': typeof ServiceOrdersIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/items/$itemId': typeof VaultItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-to-vault': typeof AddToVaultRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/dev-login': typeof DevLoginRoute
  '/extract': typeof ExtractRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/pregrade': typeof PregradeRoute
  '/pricing': typeof PricingRoute
  '/ratings': typeof RatingsRoute
  '/redemptions': typeof RedemptionsRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/scanner': typeof ScannerRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/stores': typeof StoresRoute
  '/vault-deliveries': typeof VaultDeliveriesRoute
  '/wishlist': typeof WishlistRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/profile/kyc': typeof ProfileKycRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/new': typeof SellerNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/service-orders/$orderId': typeof ServiceOrdersOrderIdRoute
  '/service-provider/$providerId': typeof ServiceProviderProviderIdRoute
  '/achievements': typeof AchievementsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/market': typeof MarketIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/seller': typeof SellerIndexRoute
  '/service-orders': typeof ServiceOrdersIndexRoute
  '/vault': typeof VaultIndexRoute
  '/vault/items/$itemId': typeof VaultItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/add-to-vault': typeof AddToVaultRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/extract': typeof ExtractRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pregrade': typeof PregradeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ratings': typeof RatingsRoute
  '/redemptions': typeof RedemptionsRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/scanner': typeof ScannerRoute
  '/seller': typeof SellerRouteWithChildren
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/stores': typeof StoresRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault-deliveries': typeof VaultDeliveriesRoute
  '/wishlist': typeof WishlistRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/profile/kyc': typeof ProfileKycRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/new': typeof SellerNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/service-orders/$orderId': typeof ServiceOrdersOrderIdRoute
  '/service-provider/$providerId': typeof ServiceProviderProviderIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/market/': typeof MarketIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/service-orders/': typeof ServiceOrdersIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/items/$itemId': typeof VaultItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/add-to-vault'
    | '/admin'
    | '/browse'
    | '/campaigns'
    | '/dev-login'
    | '/extract'
    | '/following'
    | '/login'
    | '/market'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/pregrade'
    | '/pricing'
    | '/profile'
    | '/ratings'
    | '/redemptions'
    | '/register'
    | '/scan'
    | '/scanner'
    | '/seller'
    | '/services'
    | '/settings'
    | '/status'
    | '/stores'
    | '/vault'
    | '/vault-deliveries'
    | '/wishlist'
    | '/achievements/$slug'
    | '/campaigns/$slug'
    | '/checkout/$listingId'
    | '/market/$listingId'
    | '/orders/$orderId'
    | '/profile/kyc'
    | '/seller/$sellerId'
    | '/seller/new'
    | '/seller/orders'
    | '/service-orders/$orderId'
    | '/service-provider/$providerId'
    | '/achievements/'
    | '/campaigns/'
    | '/market/'
    | '/orders/'
    | '/profile/'
    | '/seller/'
    | '/service-orders/'
    | '/vault/'
    | '/vault/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-to-vault'
    | '/admin'
    | '/browse'
    | '/dev-login'
    | '/extract'
    | '/following'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/pregrade'
    | '/pricing'
    | '/ratings'
    | '/redemptions'
    | '/register'
    | '/scan'
    | '/scanner'
    | '/services'
    | '/settings'
    | '/status'
    | '/stores'
    | '/vault-deliveries'
    | '/wishlist'
    | '/achievements/$slug'
    | '/campaigns/$slug'
    | '/checkout/$listingId'
    | '/market/$listingId'
    | '/orders/$orderId'
    | '/profile/kyc'
    | '/seller/$sellerId'
    | '/seller/new'
    | '/seller/orders'
    | '/service-orders/$orderId'
    | '/service-provider/$providerId'
    | '/achievements'
    | '/campaigns'
    | '/market'
    | '/orders'
    | '/profile'
    | '/seller'
    | '/service-orders'
    | '/vault'
    | '/vault/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/add-to-vault'
    | '/admin'
    | '/browse'
    | '/campaigns'
    | '/dev-login'
    | '/extract'
    | '/following'
    | '/login'
    | '/market'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/pregrade'
    | '/pricing'
    | '/profile'
    | '/ratings'
    | '/redemptions'
    | '/register'
    | '/scan'
    | '/scanner'
    | '/seller'
    | '/services'
    | '/settings'
    | '/status'
    | '/stores'
    | '/vault'
    | '/vault-deliveries'
    | '/wishlist'
    | '/achievements/$slug'
    | '/campaigns/$slug'
    | '/checkout/$listingId'
    | '/market/$listingId'
    | '/orders/$orderId'
    | '/profile/kyc'
    | '/seller/$sellerId'
    | '/seller/new'
    | '/seller/orders'
    | '/service-orders/$orderId'
    | '/service-provider/$providerId'
    | '/achievements/'
    | '/campaigns/'
    | '/market/'
    | '/orders/'
    | '/profile/'
    | '/seller/'
    | '/service-orders/'
    | '/vault/'
    | '/vault/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRouteWithChildren
  AddToVaultRoute: typeof AddToVaultRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  DevLoginRoute: typeof DevLoginRoute
  ExtractRoute: typeof ExtractRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PregradeRoute: typeof PregradeRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RatingsRoute: typeof RatingsRoute
  RedemptionsRoute: typeof RedemptionsRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  ScannerRoute: typeof ScannerRoute
  SellerRoute: typeof SellerRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  StoresRoute: typeof StoresRoute
  VaultRoute: typeof VaultRouteWithChildren
  VaultDeliveriesRoute: typeof VaultDeliveriesRoute
  WishlistRoute: typeof WishlistRoute
  CheckoutListingIdRoute: typeof CheckoutListingIdRoute
  ServiceOrdersOrderIdRoute: typeof ServiceOrdersOrderIdRoute
  ServiceProviderProviderIdRoute: typeof ServiceProviderProviderIdRoute
  ServiceOrdersIndexRoute: typeof ServiceOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-deliveries': {
      id: '/vault-deliveries'
      path: '/vault-deliveries'
      fullPath: '/vault-deliveries'
      preLoaderRoute: typeof VaultDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redemptions': {
      id: '/redemptions'
      path: '/redemptions'
      fullPath: '/redemptions'
      preLoaderRoute: typeof RedemptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregrade': {
      id: '/pregrade'
      path: '/pregrade'
      fullPath: '/pregrade'
      preLoaderRoute: typeof PregradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-to-vault': {
      id: '/add-to-vault'
      path: '/add-to-vault'
      fullPath: '/add-to-vault'
      preLoaderRoute: typeof AddToVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/service-orders/': {
      id: '/service-orders/'
      path: '/service-orders'
      fullPath: '/service-orders/'
      preLoaderRoute: typeof ServiceOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof AchievementsRoute
    }
    '/service-provider/$providerId': {
      id: '/service-provider/$providerId'
      path: '/service-provider/$providerId'
      fullPath: '/service-provider/$providerId'
      preLoaderRoute: typeof ServiceProviderProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-orders/$orderId': {
      id: '/service-orders/$orderId'
      path: '/service-orders/$orderId'
      fullPath: '/service-orders/$orderId'
      preLoaderRoute: typeof ServiceOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/new': {
      id: '/seller/new'
      path: '/new'
      fullPath: '/seller/new'
      preLoaderRoute: typeof SellerNewRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/$sellerId': {
      id: '/seller/$sellerId'
      path: '/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof SellerSellerIdRouteImport
      parentRoute: typeof SellerRoute
    }
    '/profile/kyc': {
      id: '/profile/kyc'
      path: '/kyc'
      fullPath: '/profile/kyc'
      preLoaderRoute: typeof ProfileKycRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/market/$listingId': {
      id: '/market/$listingId'
      path: '/$listingId'
      fullPath: '/market/$listingId'
      preLoaderRoute: typeof MarketListingIdRouteImport
      parentRoute: typeof MarketRoute
    }
    '/checkout/$listingId': {
      id: '/checkout/$listingId'
      path: '/checkout/$listingId'
      fullPath: '/checkout/$listingId'
      preLoaderRoute: typeof CheckoutListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/achievements/$slug': {
      id: '/achievements/$slug'
      path: '/$slug'
      fullPath: '/achievements/$slug'
      preLoaderRoute: typeof AchievementsSlugRouteImport
      parentRoute: typeof AchievementsRoute
    }
    '/vault/items/$itemId': {
      id: '/vault/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/vault/items/$itemId'
      preLoaderRoute: typeof VaultItemsItemIdRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface AchievementsRouteChildren {
  AchievementsSlugRoute: typeof AchievementsSlugRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
}

const AchievementsRouteChildren: AchievementsRouteChildren = {
  AchievementsSlugRoute: AchievementsSlugRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
}

const AchievementsRouteWithChildren = AchievementsRoute._addFileChildren(
  AchievementsRouteChildren,
)

interface CampaignsRouteChildren {
  CampaignsSlugRoute: typeof CampaignsSlugRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsSlugRoute: CampaignsSlugRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface MarketRouteChildren {
  MarketListingIdRoute: typeof MarketListingIdRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketListingIdRoute: MarketListingIdRoute,
  MarketIndexRoute: MarketIndexRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProfileRouteChildren {
  ProfileKycRoute: typeof ProfileKycRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileKycRoute: ProfileKycRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SellerRouteChildren {
  SellerSellerIdRoute: typeof SellerSellerIdRoute
  SellerNewRoute: typeof SellerNewRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerSellerIdRoute: SellerSellerIdRoute,
  SellerNewRoute: SellerNewRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

interface VaultRouteChildren {
  VaultIndexRoute: typeof VaultIndexRoute
  VaultItemsItemIdRoute: typeof VaultItemsItemIdRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultIndexRoute: VaultIndexRoute,
  VaultItemsItemIdRoute: VaultItemsItemIdRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRouteWithChildren,
  AddToVaultRoute: AddToVaultRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  DevLoginRoute: DevLoginRoute,
  ExtractRoute: ExtractRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PregradeRoute: PregradeRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RatingsRoute: RatingsRoute,
  RedemptionsRoute: RedemptionsRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  ScannerRoute: ScannerRoute,
  SellerRoute: SellerRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  StoresRoute: StoresRoute,
  VaultRoute: VaultRouteWithChildren,
  VaultDeliveriesRoute: VaultDeliveriesRoute,
  WishlistRoute: WishlistRoute,
  CheckoutListingIdRoute: CheckoutListingIdRoute,
  ServiceOrdersOrderIdRoute: ServiceOrdersOrderIdRoute,
  ServiceProviderProviderIdRoute: ServiceProviderProviderIdRoute,
  ServiceOrdersIndexRoute: ServiceOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
